### ISSUE TITLE
Support go.uber.org/mock

### ISSUE THREAD

**Issue by tmc** [budougumi0617/cmpmock#3]
As go.uber.org/mock has taken over maintenance of gomock, this project should change to support it.

In the mean time I have a fork that does so published here: https://github.com/tmc/cmpmock

**Comment by budougumi0617** [comment]
@tmc Thank you very much for the very important issue!! Although it was significantly delayed, I have released v0.1.0 and started using go.uber.org/mock.

https://github.com/budougumi0617/cmpmock/releases/tag/v0.1.0

I sincerely apologize for the delay in responding.

great thanx!!!
